id: A1B5B4BCF
title: 'CII_§XXVI: The Bodhisattva Assumes Various Personalities'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.025958
  last_modified_at: 2022-03-01 21:40:54.025961
