id: A1B5B4BCF
title: 'CII_§VII: Erroneous Views held by Some Brahmans and Śramanas Concerning Causation,
  Continuation, etc.; The Buddhist Views Concerning Such Subjects as Alayavijñāna,
  Nirvana, Mind-only, etc.; Attainments of the Bodhisattva'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.964689
  last_modified_at: 2022-03-01 21:40:53.964692
