id: A1B5B4BCF
title: 'CII_§III: “The One Hundred and Eight Negations”, verse 98'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.954128
  last_modified_at: 2022-03-01 21:40:53.954131
