id: A1B5B4BCF
title: CII_§IX: The Evolution and Function of the Vijñānas; The Spiritual Discipline
  of the Bodhisattva; Verses on the Ālaya-ocean and Vijñāna-waves
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.958611
  last_modified_at: 2022-03-01 21:40:53.958614
