id: A1B5B4BCF
title: CV_Verse 431-440
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.230520
  last_modified_at: 2022-03-01 21:40:54.230523
