id: A1B5B4BCF
title: CII_§XVI: The Śrāvaka's Realisation and Attachment to the Notion of Self-nature
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.007629
  last_modified_at: 2022-03-01 21:40:54.007632
