id: A1B5B4BCF
title: CII_§VIII: The Bodhisattva's Discipling himself in Self-realisation
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.966972
  last_modified_at: 2022-03-01 21:40:53.966975
