id: A1B5B4BCF
title: CII_§XIII: Verses on the Ālayavijñāna and Mind-only, verse 123-127
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.976994
  last_modified_at: 2022-03-01 21:40:53.976998
