id: A1B5B4BCF
title: CI_Verse 4-44
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.080248
  last_modified_at: 2022-03-01 21:40:54.080251
