id: A1B5B4BCF
title: 'CII_§XXVII: On Emptiness (śūnyatā), No-birth, and Non-duality'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.030301
  last_modified_at: 2022-03-01 21:40:54.030304
