id: A1B5B4BCF
title: 'CII_§XX: The Five Classes of Spiritual Insight'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.013273
  last_modified_at: 2022-03-01 21:40:54.013276
