id: A1B5B4BCF
title: 'CII_§XXIX: A Verse on the Philosophers'' Discriminations, verse 137'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.022562
  last_modified_at: 2022-03-01 21:40:54.022565
