id: A1B5B4BCF
title: CIV_Verse 11-20
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.061469
  last_modified_at: 2022-03-01 21:40:54.061472
