id: A1B5B4BCF
title: 'CII_§XXX: The Four Things Needed for the Constitution of Bodhisattvahood'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.034873
  last_modified_at: 2022-03-01 21:40:54.034876
