id: A1B5B4BCF
title: 'CII_§XXI: Verses on the Triple Vehicle, verse 128-131'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.015437
  last_modified_at: 2022-03-01 21:40:54.015440
