id: A1B5B4BCF
title: CV_Verse 641-650
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.320343
  last_modified_at: 2022-03-01 21:40:54.320347
