id: A1B5B4BCF
title: CII_§XI(b): The Attainment of the Tathāgatakāya
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.971612
  last_modified_at: 2022-03-01 21:40:53.971615
