id: A1B5B4BCF
title: 'CII_§XXXIV: Verses on Reality and its Representations, verse 145-148'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.045168
  last_modified_at: 2022-03-01 21:40:54.045171
