id: A1B5B4BCF
title: 'CII_§I: Mahāmati Praises the Buddha with Verses, verse 1-8'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.946433
  last_modified_at: 2022-03-01 21:40:53.946437
