id: A1B5B4BCF
title: CII_Verse 161-64
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.913749
  last_modified_at: 2022-03-01 21:40:53.913752
