id: A1B5B4BCF
title: CII_§XIV: Purification of the Outflows, Instantaneous and Gradual
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.978868
  last_modified_at: 2022-03-01 21:40:53.978871
