id: A1B5B4BCF
title: 'CII_§VI: Seven Kinds of First Principle (paramārtha), and the Philosophers’
  Wrong Views regarding the Mind Rejected'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.962659
  last_modified_at: 2022-03-01 21:40:53.962662
