id: A1B5B4BCF
title: 'CII_§XXXI: On Causation (Six Kinds), and the Rise of Existence'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.039124
  last_modified_at: 2022-03-01 21:40:54.039127
