id: A1B5B4BCF
title: 'CII_§XXXIII: On Word and Discrimination and the Highest Reality'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.042943
  last_modified_at: 2022-03-01 21:40:54.042945
