id: A1B5B4BCF
title: 'CII_§XXXVIII: On Nirvāṇa])Four Kinds of Dhyāna'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.054451
  last_modified_at: 2022-03-01 21:40:54.054455
