id: A1B5B4BCF
title: CII_verse 26-50
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.928172
  last_modified_at: 2022-03-01 21:40:53.928176
