id: A1B5B4BCF
title: CII_§X: The Bodhisattva is to Understand the Signification of Mind-only
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.968429
  last_modified_at: 2022-03-01 21:40:53.968432
