id: A1B5B4BCF
title: 'CII_§XXXII: Four Forms of Word-discrimination'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.041070
  last_modified_at: 2022-03-01 21:40:54.041073
