id: A1B5B4BCF
title: CII_§XI(a): The Three Aspects of Noble Wisdom (āryajñāna).
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.970087
  last_modified_at: 2022-03-01 21:40:53.970090
