id: A1B5B4BCF
title: 'CII_§XXXV: Mind-only, Multitudinousness, and Analogies, with an Interpolation
  on the Dualistic Notion of Existence'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.048779
  last_modified_at: 2022-03-01 21:40:54.048782
