id: A1B5B4BCF
title: CHAPTER SEVEN. ON TRANSFORMATION
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.792412
  last_modified_at: 2022-03-01 21:40:53.792420
