id: A1B5B4BCF
title: 'CII_§XXXIX: Two Characteristics of Self-nature'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:54.046740
  last_modified_at: 2022-03-01 21:40:54.046743
