id: A1B5B4BCF
title: 'CII_§II: Mahāmati''s “One Hundred and Eight Questions”, verse 9-25'
type: translation
source_metadata:
  languages:
  - zh
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:40:53.951991
  last_modified_at: 2022-03-01 21:40:53.951995
